#!/bin/bash

# Syspulse Agent Orchestration System
# Creates structured roadmap directories for Syspulse Fortress

set -e

CHECKLIST_BASE="./_DIR_"
AGENTS=("a1" "a2" "a3" "a4" "a5")
GOALS=("g1" "g2" "g3" "g4" "g5")
COMPONENTS=("citadel" "gatehouse" "sentries" "ramparts" "moat" "drawbridge" "keep" "watchtower" "armory" "lookouts" "herald" "scribe" "quartermaster" "scout" "beacon" "blacksmith" "healer" "siege_engine" "stable_master" "war_council" "throne" "squires" "oracles" "sanctum" "ledger" "annals")
WORKER_TYPES=("General" "Security" "Monitoring" "Maintenance")

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

# Show usage
show_usage() {
    echo -e "${CYAN}Syspulse Agent Orchestration System${NC}"
    echo -e "${CYAN}====================================${NC}"
    echo
    echo "Usage: $0 <command> [options]"
    echo
    echo "Commands:"
    echo "  create <objective>    Create new objective with agent structure"
    echo "  list                  List all objectives"
    echo "  status <objective>    Show objective status"
    echo "  blockers <objective>  List blocked goals"
    echo "  plan <objective>      Generate master plan"
    echo "  help                  Show this help"
    echo
    echo "Structure created:"
    echo "  checklist/"
    echo "  └── <objective>/"
    echo "      ├── master_prompt.txt"
    echo "      ├── master.log"
    echo "      ├── plan.md"
    echo "      ├── a1/ (Agent 1)"
    echo "      │   ├── g1/ (Goal 1)"
    echo "      │   │   ├── prompt.txt"
    echo "      │   │   ├── followup-prompt.txt"
    echo "      │   │   └── roadmap.md"
    echo "      │   └── g2-g5/ (Goals 2-5)"
    echo "      └── a2-a5/ (Agents 2-5)"
    echo
}

# Create objective structure
create_objective() {
    local objective="$1"
    
    if [[ -z "$objective" ]]; then
        echo -e "${RED}Error: Objective name required${NC}"
        echo "Usage: $0 create <objective>"
        exit 1
    fi
    
    objective=$(echo "$objective" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9_-]/_/g')
    local objective_dir="$CHECKLIST_BASE/$objective"
    
    if [[ -d "$objective_dir" ]]; then
        echo -e "${YELLOW}Warning: Objective '$objective' already exists${NC}"
        read -p "Do you want to recreate it? (y/N): " -n 1 -r
        echo
        if [[ ! $REPLY =~ ^[Yy]$ ]]; then
            exit 0
        fi
        rm -rf "$objective_dir"
    fi
    
    echo -e "${CYAN}Creating objective: $objective${NC}"
    mkdir -p "$objective_dir"
    
    touch "$objective_dir/master.log"
    echo "$(date): Objective $objective created" >> "$objective_dir/master.log"
    cat > "$objective_dir/plan.md" << EOF
# Master Plan: $objective

## Timeline
[Generated by Throne: Run checklist.sh plan $objective]

## Dependency Graph
[Generated by Throne: Run checklist.sh plan $objective]

## Worker Assignments
[Generated by Throne: Run checklist.sh plan $objective]
EOF

    for agent in "${AGENTS[@]}"; do
        local agent_dir="$objective_dir/$agent"
        mkdir -p "$agent_dir"
        echo -e "  ${GREEN}Agent $agent${NC}"
        
        for goal in "${GOALS[@]}"; do
            local goal_dir="$agent_dir/$goal"
            mkdir -p "$goal_dir"
            
            cat > "$goal_dir/prompt.txt" << EOF
# $objective - Agent $agent - Goal $goal

## Context
You are Agent $agent working on the Syspulse Fortress objective: $objective
This is Goal $goal out of 5, aligned with component: [SPECIFY COMPONENT]

## Your Mission
[DESCRIBE WHAT THIS AGENT SHOULD ACCOMPLISH, e.g., Implement syspulse citadel start]

## Requirements
- Execute tasks in /opt/syspulse/<component>
- Update /opt/syspulse/ledger and /opt/syspulse/annals
- Report progress via syspulse squires report
- Follow roadmap.md checklist

## Success Criteria
[DEFINE SUCCESS, e.g., CLI command syspulse citadel start runs without errors]

## Resources Available
- Syspulse Fortress: /opt/syspulse
- Database: /opt/syspulse/ledger
- Logging: /opt/syspulse/annals
- CLI: syspulse <component> <command>

## Instructions
1. Review roadmap.md for tasks
2. Execute CLI commands as specified
3. Update roadmap.md status and notes
4. Verify with syspulse lookouts metrics
5. Report to Throne
EOF

            cat > "$goal_dir/followup-prompt.txt" << EOF
# Follow-up: $objective - Agent $agent - Goal $goal

## Post-Completion Actions
1. **Verification**
   - Test functionality with syspulse lookouts metrics
   - Ensure integration with /opt/syspulse/<component>
   - Check for regressions via syspulse keep integrity

2. **Documentation**
   - Update /opt/syspulse/courtyard/README.md
   - Document CLI commands in /opt/syspulse/edicts
   - Log results in /opt/syspulse/annals

3. **Integration**
   - Update syspulse throne coordinate
   - Ensure compatibility with Sanctum services
   - Update CLI help text

4. **Cleanup**
   - Remove temporary files
   - Optimize code in /opt/syspulse/<component>
   - Update /opt/syspulse/ledger schema

5. **Reporting**
   - Mark goal completed in roadmap.md
   - Report via syspulse throne squires report
   - Suggest improvements in /opt/syspulse/suggestions.md
EOF

            cat > "$goal_dir/roadmap.md" << EOF
# Roadmap: $objective - Agent $agent - Goal $goal

## Overview
- **Objective**: $objective
- **Agent**: $agent
- **Goal**: $goal
- **Component**: Not Set
- **Priority**: Medium
- **Estimated Duration**: Not Set
- **Dependencies**: None
- **Worker Type**: General
- **Last Updated**: $(date)

## Pre-Implementation
- [ ] Review prompt.txt for goal-specific mission and requirements
- [ ] Confirm dependencies (e.g., component functionality) are complete
- [ ] Analyze current system state (e.g., check /opt/syspulse/<component>)
- [ ] Plan implementation steps and resource needs
- [ ] Assign worker from pool (type: General)

## Implementation
- [ ] Create/modify files in /opt/syspulse/<component>
- [ ] Implement core functionality (e.g., syspulse <component> <command>)
- [ ] Add error handling and logging to /opt/syspulse/annals
- [ ] Update database schema in /opt/syspulse/ledger if needed
- [ ] Validate against success criteria in prompt.txt

## Testing
- [ ] Run unit tests for <component> functionality
- [ ] Perform integration tests with dependent components
- [ ] Conduct manual tests for CLI commands
- [ ] Verify performance metrics via syspulse lookouts metrics
- [ ] Log test results to /opt/syspulse/annals

## Integration
- [ ] Update Throne orchestrator (syspulse throne coordinate)
- [ ] Integrate with Sanctum services (syspulse sanctum services status)
- [ ] Update CLI interface (syspulse <component> --help)
- [ ] Verify compatibility with other agents’ goals
- [ ] Update /opt/syspulse/README.md

## Documentation
- [ ] Add code comments in /opt/syspulse/<component>
- [ ] Update user documentation in /opt/syspulse/courtyard
- [ ] Document CLI commands and configuration in edicts
- [ ] Record deviations in Notes section
- [ ] Submit documentation for review

## Completion
- [ ] Verify functionality meets prompt.txt success criteria
- [ ] Ensure all tests pass (syspulse lookouts metrics)
- [ ] Confirm documentation is complete
- [ ] Check for regressions via syspulse keep integrity
- [ ] Mark goal ready for production

## Post-Completion
- [ ] Update status to "Completed" in this roadmap
- [ ] Report to Throne (syspulse throne squires report)
- [ ] Clean up temporary files in /opt/syspulse
- [ ] Log metrics to /opt/syspulse/annals
- [ ] Suggest optimizations in /opt/syspulse/suggestions.md

## Status
- [x] Not Started
- [ ] In Progress
- [ ] Completed
- [ ] Blocked

## Notes
- **Blockers**: None
- **Progress Updates**: None
- **Master Instructions**: None
EOF

            echo -e "    ${YELLOW}Goal $goal${NC} - Files created"
        done
    done
    
    cat > "$objective_dir/README.md" << EOF
# Objective: $objective

Created: $(date)

## Structure
This objective is divided among 5 agents, each with 5 goals aligned with Syspulse components:

EOF

    for agent in "${AGENTS[@]}"; do
        echo "### Agent $agent" >> "$objective_dir/README.md"
        echo "- Goal 1: [To be defined]" >> "$objective_dir/README.md"
        echo "- Goal 2: [To be defined]" >> "$objective_dir/README.md"
        echo "- Goal 3: [To be defined]" >> "$objective_dir/README.md"
        echo "- Goal 4: [To be defined]" >> "$objective_dir/README.md"
        echo "- Goal 5: [To be defined]" >> "$objective_dir/README.md"
        echo "" >> "$objective_dir/README.md"
    done
    
    cat >> "$objective_dir/README.md" << EOF
## Usage
Agents implement Syspulse components based on /opt/tusk_and_tsk/syspulse.tsk. Update roadmap.md for progress.

## Status Tracking
Use roadmap.md for goal details. Run checklist.sh status <objective> for summaries.

## Completion
Objective complete when all 25 goals are verified via syspulse lookouts metrics.
EOF
    
    echo -e "${GREEN}✓ Objective '$objective' created successfully${NC}"
    echo -e "  ${CYAN}Location: $objective_dir${NC}"
    echo -e "  ${CYAN}Agents: 5 (a1-a5)${NC}"
    echo -e "  ${CYAN}Goals per agent: 5 (g1-g5)${NC}"
    echo -e "  ${CYAN}Total goals: 25${NC}"
}

# Generate master plan
plan_objective() {
    local objective="$1"
    
    if [[ -z "$objective" ]]; then
        echo -e "${RED}Error: Objective name required${NC}"
        echo "Usage: $0 plan <objective>"
        exit 1
    fi
    
    local objective_dir="$CHECKLIST_BASE/$objective"
    if [[ ! -d "$objective_dir" ]]; then
        echo -e "${RED}Error: Objective '$objective' not found${NC}"
        exit 1
    fi
    
    echo -e "${CYAN}Generating master plan for: $objective${NC}"
    local plan_file="$objective_dir/plan.md"
    
    echo "# Master Plan: $objective" > "$plan_file"
    echo -e "\n## Timeline" >> "$plan_file"
    echo "| Goal | Agent | Component | Priority | Duration | Status |" >> "$plan_file"
    echo "|------|-------|-----------|----------|----------|--------|" >> "$plan_file"
    
    local total_duration=0
    for agent in "${AGENTS[@]}"; do
        for goal in "${GOALS[@]}"; do
            local roadmap_file="$objective_dir/$agent/$goal/roadmap.md"
            if [[ -f "$roadmap_file" ]]; then
                local component=$(grep "Component" "$roadmap_file" | sed 's/.*: //')
                local priority=$(grep "Priority" "$roadmap_file" | sed 's/.*: //')
                local duration=$(grep "Estimated Duration" "$roadmap_file" | sed 's/.*: //')
                local status=$(grep -A1 "Status" "$roadmap_file" | grep -E "\[[x ]\]" | sed 's/.*\[\([x ]\)\].*/\1/' | { [[ $(cat) == "x" ]] && echo "Started" || echo "Not Started"; })
                echo "| $goal | $agent | $component | $priority | $duration | $status |" >> "$plan_file"
                [[ "$duration" =~ ([0-9]+) ]] && total_duration=$((total_duration + ${BASH_REMATCH[1]}))
            fi
        done
    done
    
    echo -e "\n## Dependency Graph" >> "$plan_file"
    echo "[Dependencies to be mapped by Throne]" >> "$plan_file"
    
    echo -e "\n## Worker Assignments" >> "$plan_file"
    echo "[Assignments to be updated by Throne via syspulse throne squires assign]" >> "$plan_file"
    
    echo -e "${GREEN}✓ Master plan generated at $plan_file${NC}"
    echo "$(date): Generated master plan for $objective" >> "$objective_dir/master.log"
}

# List objectives, status, and blockers (unchanged from previous, included for completeness)
list_objectives() {
    echo -e "${CYAN}Available Objectives:${NC}"
    echo -e "${CYAN}=====================${NC}"
    
    if [[ ! -d "$CHECKLIST_BASE" ]]; then
        echo -e "${YELLOW}No objectives found. Use 'create' to add one.${NC}"
        return
    fi
    
    local count=0
    for objective_dir in "$CHECKLIST_BASE"/*; do
        if [[ -d "$objective_dir" ]]; then
            local objective=$(basename "$objective_dir")
            echo -e "  ${GREEN}$objective${NC}"
            
            local total_goals=0
            local completed_goals=0
            
            for agent in "${AGENTS[@]}"; do
                for goal in "${GOALS[@]}"; do
                    local roadmap_file="$objective_dir/$agent/$goal/roadmap.md"
                    if [[ -f "$roadmap_file" ]]; then
                        total_goals=$((total_goals + 1))
                        if grep -q "Status: .*Completed" "$roadmap_file" 2>/dev/null; then
                            completed_goals=$((completed_goals + 1))
                        fi
                    fi
                done
            done
            
            echo -e "    Progress: $completed_goals/$total_goals goals completed"
            count=$((count + 1))
        fi
    done
    
    if [[ $count -eq 0 ]]; then
        echo -e "${YELLOW}No objectives found.${NC}"
    fi
}

show_status() {
    local objective="$1"
    
    if [[ -z "$objective" ]]; then
        echo -e "${RED}Error: Objective name required${NC}"
        echo "Usage: $0 status <objective>"
        exit 1
    fi
    
    local objective_dir="$CHECKLIST_BASE/$objective"
    
    if [[ ! -d "$objective_dir" ]]; then
        echo -e "${RED}Error: Objective '$objective' not found${NC}"
        exit 1
    fi
    
    echo -e "${CYAN}Objective Status: $objective${NC}"
    echo -e "${CYAN}===============================${NC}"
    echo
    
    for agent in "${AGENTS[@]}"; do
        echo -e "${GREEN}Agent $agent:${NC}"
        
        for goal in "${GOALS[@]}"; do
            local roadmap_file="$objective_dir/$agent/$goal/roadmap.md"
            local status="Not Started"
            local color="${RED}"
            
            if [[ -f "$roadmap_file" ]]; then
                if grep -q "Status: .*Completed" "$roadmap_file" 2>/dev/null; then
                    status="Completed"
                    color="${GREEN}"
                elif grep -q "Status: .*In Progress" "$roadmap_file" 2>/dev/null; then
                    status="In Progress"
                    color="${YELLOW}"
                elif grep -q "Status: .*Blocked" "$roadmap_file" 2>/dev/null; then
                    status="Blocked"
                    color="${RED}"
                fi
            fi
            
            echo -e "  Goal $goal: ${color}$status${NC}"
        done
        echo
    done
}

list_blockers() {
    local objective="$1"
    
    if [[ -z "$objective" ]]; then
        echo -e "${RED}Error: Objective name required${NC}"
        echo "Usage: $0 blockers <objective>"
        exit 1
    fi
    
    local objective_dir="$CHECKLIST_BASE/$objective"
    
    if [[ ! -d "$objective_dir" ]]; then
        echo -e "${RED}Error: Objective '$objective' not found${NC}"
        exit 1
    fi
    
    echo -e "${CYAN}Blockers for Objective: $objective${NC}"
    echo -e "${CYAN}===============================${NC}"
    echo
    
    local has_blockers=0
    for agent in "${AGENTS[@]}"; do
        for goal in "${GOALS[@]}"; do
            local roadmap_file="$objective_dir/$agent/$goal/roadmap.md"
            if [[ -f "$roadmap_file" ]] && grep -q "Status: .*Blocked" "$roadmap_file"; then
                has_blockers=1
                echo -e "${RED}Agent $agent, Goal $goal: Blocked${NC}"
                grep "Blockers:" "$roadmap_file" | sed 's/Blockers:/    Blockers:/'
                grep "Notes:" "$roadmap_file" | sed 's/Notes:/    Notes:/'
                echo
            fi
        done
    done
    
    if [[ $has_blockers -eq 0 ]]; then
        echo -e "${GREEN}No blockers found.${NC}"
    fi
}

# Main command handling
case "${1:-}" in
    "create")
        create_objective "$2"
        ;;
    "list")
        list_objectives
        ;;
    "status")
        show_status "$2"
        ;;
    "blockers")
        list_blockers "$2"
        ;;
    "plan")
        plan_objective "$2"
        ;;
    "help"|"--help"|"-h")
        show_usage
        ;;
    "")
        show_usage
        ;;
    *)
        echo -e "${RED}Error: Unknown command '$1'${NC}"
        echo
        show_usage
        exit 1
        ;;
esac