global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # TuskTsk SDK Containers
  - job_name: 'tusktsk-python'
    static_configs:
      - targets: ['tusktsk-python:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'tusktsk-javascript'
    static_configs:
      - targets: ['tusktsk-javascript:3000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'tusktsk-go'
    static_configs:
      - targets: ['tusktsk-go:8080']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'tusktsk-rust'
    static_configs:
      - targets: ['tusktsk-rust:8080']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'tusktsk-dotnet'
    static_configs:
      - targets: ['tusktsk-dotnet:5000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'tusktsk-php'
    static_configs:
      - targets: ['tusktsk-php:9000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'tusktsk-ruby'
    static_configs:
      - targets: ['tusktsk-ruby:3000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Database Services
  - job_name: 'mysql'
    static_configs:
      - targets: ['mysql:3306']
    scrape_interval: 30s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb:27017']
    scrape_interval: 30s

  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch:9200']
    metrics_path: '/_prometheus/metrics'
    scrape_interval: 30s

  # Message Queue Services
  - job_name: 'nats'
    static_configs:
      - targets: ['nats:8222']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # Docker containers
  - job_name: 'docker'
    static_configs:
      - targets: ['docker.for.mac.localhost:9323']
    scrape_interval: 30s 