# TuskLang Bash SDK - Release Workflow
# ====================================
# Releases the Bash SDK to GitHub with proper versioning and artifacts
# Version: 1.0.0

name: Release Bash SDK

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Bash SDK
        run: |
          cd sdk/bash
          chmod +x *.sh
          echo "${{ github.ref_name }}" > VERSION
      
      - name: Create package
        run: |
          cd sdk/bash
          mkdir -p ../../release/tusklang-bash-sdk
          cp *.sh ../../release/tusklang-bash-sdk/
          cp VERSION ../../release/tusklang-bash-sdk/
          cp README.md ../../release/tusklang-bash-sdk/ 2>/dev/null || true
          cp LICENSE ../../release/tusklang-bash-sdk/ 2>/dev/null || true
          cp -r sdk/ ../../release/tusklang-bash-sdk/ 2>/dev/null || true
      
      - name: Create install script
        run: |
          cd sdk/bash
          echo '#!/bin/bash' > ../../release/tusklang-bash-sdk/install.sh
          echo 'set -e' >> ../../release/tusklang-bash-sdk/install.sh
          echo 'sudo mkdir -p /opt/tusklang' >> ../../release/tusklang-bash-sdk/install.sh
          echo 'sudo cp -r * /opt/tusklang/' >> ../../release/tusklang-bash-sdk/install.sh
          echo 'sudo chmod +x /opt/tusklang/*.sh' >> ../../release/tusklang-bash-sdk/install.sh
          echo 'sudo ln -sf /opt/tusklang/tsk.sh /usr/local/bin/tsk' >> ../../release/tusklang-bash-sdk/install.sh
          echo 'echo "TuskLang Bash SDK installed successfully!"' >> ../../release/tusklang-bash-sdk/install.sh
          chmod +x ../../release/tusklang-bash-sdk/install.sh
      
      - name: Create archive
        run: |
          cd release
          tar -czf tusklang-bash-sdk-${{ github.ref_name }}.tar.gz tusklang-bash-sdk/
          zip -r tusklang-bash-sdk-${{ github.ref_name }}.zip tusklang-bash-sdk/
      
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: TuskLang Bash SDK ${{ github.ref_name }}
          body: |
            ## TuskLang Bash SDK ${{ github.ref_name }}
            
            ### Installation
            ```bash
            wget https://github.com/cyber-boost/tusktsk/releases/download/${{ github.ref_name }}/tusklang-bash-sdk-${{ github.ref_name }}.tar.gz
            tar -xzf tusklang-bash-sdk-${{ github.ref_name }}.tar.gz
            cd tusklang-bash-sdk-${{ github.ref_name }}
            sudo ./install.sh
            ```
          draft: false
          prerelease: false
      
      - name: Upload Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release/tusklang-bash-sdk-${{ github.ref_name }}.tar.gz
          asset_name: tusklang-bash-sdk-${{ github.ref_name }}.tar.gz
          asset_content_type: application/gzip
      
      - name: Upload ZIP
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release/tusklang-bash-sdk-${{ github.ref_name }}.zip
          asset_name: tusklang-bash-sdk-${{ github.ref_name }}.zip
          asset_content_type: application/zip 